version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cheatah_slack
    ports:
      - '3306:3306'
  app:
    image: 787647415306.dkr.ecr.ap-northeast-1.amazonaws.com/cheatah/cheatah-slack:latest
    command: npm start
    links:
      - db
    ports:
      - '80:80'
    environment:
      DB_PORT: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cheatah_slack
      SLACK_CLIENT: ${SLACK_CLIENT}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
