machine:
  node:
    version: 7.10.0

machine:
  services:
    - docker
dependencies:
  pre:
    - pip install docker-compose
test:
  pre:
    - sudo docker-compose up -d
  override:
    - docker-compose run npm test
deployment:
  prod:
    branch: master
    commands:
      - ./deploy.sh